### ISSUE TITLE
LiveReload no more work

### ISSUE THREAD

**Issue by Riduidel** [Riduidel/agile-architecture-documentation-system#136]
Two things doesn't work

1. ~~The fizzed-watcher-maven-plugin doesn't trigger a build when file is changed~~
2. The livereload extension doesn't seems to work

**Comment by Bullfrog666** [comment]
Fizzed-watcher-maven-plugin seems working, just a bit slow on mac.

**Comment by Bullfrog666** [comment]
Fizzed-watcher-maven-plugin seems not be triggered by the files in src/docs/asciidoc.
The modification of a file in src/main/java trigger the rebuild in the next 10sec maximum.

**Comment by Bullfrog666** [comment]
is "${project.basedir}" the problem in the path ?
where is this variable declared ?

**Comment by Bullfrog666** [comment]
`[INFO] --- fizzed-watcher-maven-plugin:1.0.6:run (default) @ architecture-documentation ---
[INFO] Registering 2 watch sets...
[INFO] Registering watch set: FileSet {directory: /Users/sycz/Stage/agile-architecture-documentation-system/architecture-documentation/src/main/java, PatternSet [includes: {}, excludes: {}]}
[INFO] Watcher - registering watch on dir: /Users/sycz/Stage/agile-architecture-documentation-system/architecture-documentation/src/main/java
[INFO] Watcher - registering watch on dir: /Users/sycz/Stage/agile-architecture-documentation-system/architecture-documentation/src/main/java/org
[INFO] Watcher - registering watch on dir: /Users/sycz/Stage/agile-architecture-documentation-system/architecture-documentation/src/main/java/org/ndx
[INFO] Watcher - registering watch on dir: /Users/sycz/Stage/agile-architecture-documentation-system/architecture-documentation/src/main/java/org/ndx/agile
[INFO] Watcher - registering watch on dir: /Users/sycz/Stage/agile-architecture-documentation-system/architecture-documentation/src/main/java/org/ndx/agile/architecture
[INFO] Watcher - registering watch on dir: /Users/sycz/Stage/agile-architecture-documentation-system/architecture-documentation/src/main/java/org/ndx/agile/architecture/documentation
[INFO] Watcher - registering watch on dir: /Users/sycz/Stage/agile-architecture-documentation-system/architecture-documentation/src/main/java/org/ndx/agile/architecture/documentation/system
[INFO] Registering watch set: FileSet {directory: src/slides/asciidoc, PatternSet [includes: {}, excludes: {}]}
[INFO] Watcher - registering watch on dir: src/slides/asciidoc
[INFO] Watcher - registering watch on dir: src/slides/asciidoc/images
[INFO] Watcher - waiting for changes...
`

src/docs/asciidocs not in the list above.

**Comment by Riduidel** [comment]
The livereload issue is triggered by port being used.

However, the fact that `src/docs/asciidoc` is not in the fizzed watched folders is confirmed also on my machine. I'll take care of that.

**Comment by Riduidel** [comment]
Now I remember what I made this mess of configuration ...

```
[INFO] Watcher - registering watch on dir: C:\Users\nicolas-delsaux\Documents\open-source\agile-architecture-documentation-system\architecture-documentation\src\main\java\org\ndx\agile\architecture\documentation\system
[INFO] Registering watch set: FileSet {directory: src/slides/asciidoc, PatternSet [includes: {}, excludes: {}]}
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:18 min
[INFO] Finished at: 2022-04-06T08:30:08+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.fizzed:fizzed-watcher-maven-plugin:1.0.6:run (default) on project architecture-documentation: Directory src\slides\asciidoc does not exist. Unable to watch a dir that does not exist -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

Fizzed-watcher doesn't support watching non-existing directories.
AND [profile activation based on multiple conditions is OR-ed](https://stackoverflow.com/a/4629269/15619)

Oh, wait It seems that, according to [Maven JIRA](https://issues.apache.org/jira/browse/MNG-4565), this may well be fixed ... Let me try ...
