### ISSUE TITLE
Generate sequence diagrams from sources

### ISSUE THREAD

**Issue by Z01ndels** [Riduidel/agile-architecture-documentation-system#56]
For each `Component`, we're able to have associated `CodeElement` objects (as provided by the various component discovery mechanisms).
Since we also have mechanisms to locate source files, it should be possible to analyze methods of each component, and for each of these generate sequence diagrams, recursive or not.

**Comment by Riduidel** [comment]
457c294 contains a working version which some important flaws

- It can't handle anything else than method calls (so no handlin of if/for/while/...)
- There are at least two transformations : JavaParser MethodCallExpr is transformed into a `CallInstance`, then into a `SequenceDiagramGenerator.CallRepresentation`. I'm 100% sure it would be possible to simply have the `CallInstance`, provided it is visitable.

As a consequence, this work is not yet marked as done, and I'll first work on the second point (as it implements a better architecture), then on the first
