### ISSUE TITLE
Unable to generate PlantUML diagrams

### ISSUE THREAD

**Issue by Z01ndels** [Riduidel/agile-architecture-documentation-system#68]
It seems we're unable to generate diagrams

Tyically, I get

	[ERROR] asciidoctor: ERROR: \diagrams\system.context.plantuml: Failed to generate image: PlantUML image generation failed: [From https://raw.githubusercontent.com/stawirej/C4-PlantUML/master/C4.puml (line 7) ]
	[From <input> (line 2) ]                                                              
																						  
	@startuml(id=system.context)                                                          
																						  
																						  
	!procedure ELEMENT_FONT_COLOR()                                                       
	^^^^^                                                                                 
	 Syntax Error?        

or

	[INFO] asciidoctor: ERROR: \diagrams\PASS.containers.plantuml: Failed to generate image: PlantUML image generation failed: [From https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4.puml (line 56) ]
	[From <input> (line 2) ]                                                                    
																								
	@startuml(id=PASS.containers)                                                               
																								
																								
	...                                                                                         
	... ( skipping 21 lines )                                                                   
	...                                                                                         
																								
																								
	!procedure HIDE_STEREOTYPE()                                                                
	^^^^^                                                                                       
	 Syntax Error?           

depending upon the chosen C4 library.
Error is recent.

**Comment by Riduidel** [comment]
Seems to be related to PlantUML, but the version didn't change!

**Comment by Riduidel** [comment]
Seems related to https://forum.plantuml.net/11259/procedure-throwing-syntax-official-docker-plantuml-server

**Comment by Riduidel** [comment]
Let me infer something ...
PlantUML introduced preprocessing this year (see https://plantuml.com/fr/preprocessing#01deeaa12f04fb9d).
And part of this preprocessing system is the use of `!procedure` keyword along with procedures having to start ith a `$` sign (per QA). Maybe we use badly named procedures (or at least our dependencies do).
So maybe I should fix PlantUML version to one that do not have that feature ... Let's try that. NOPE ...

**Comment by Riduidel** [comment]
Let now dive into [asciidoctorj-diagram](https://github.com/asciidoctor/asciidoctorj-diagram).
Let's look at their POM.
Do you see the dependency declaration for PlantUML ? No, you see nothing ... because asciidoctorj-diagram repackages [asciidoctor-diagram](https://asciidoctor.org/docs/asciidoctor-diagram/), which is a pure Ruby version (and things starts to get weird).

**Comment by arnaudroques** [comment]
> 
> PlantUML introduced preprocessing this year (see https://plantuml.com/fr/preprocessing#01deeaa12f04fb9d).
> And part of this preprocessing system is the use of `!procedure` keyword along with procedures having to start ith a `$` sign (per QA). Maybe we use badly named procedures (or at least our dependencies do).

Actually, the `$` is not mandatory.

**Comment by Riduidel** [comment]
So let's try to make sure how to reproduce the bug : I need a PlantUML 1.2020.6 version, so let's try a Docker container ...

	docker run -p 18888:8080 plantuml/plantuml-server:jetty-v1.2020.6
	Unable to find image 'plantuml/plantuml-server:jetty-v1.2020.6' locally
	docker: Error response from daemon: manifest for plantuml/plantuml-server:jetty-v1.2020.6 not found: manifest unknown: manifest unknown.
	See 'docker run --help'.

[narrator voice] And indeed, this version is not on Docker Hub 🤣

**Comment by Riduidel** [comment]
So, from what I understand, the clean way to do things would be to gently ask asciidoctor-diagram to publish a new version of their gem using a new version of PlantUML, then to have asciidoctorj-diagram use this new version.

I'm not gonna lie, this looks like international diplomacy to me.

So there may be another way.

And you know there is one ...

The other way is to use asciidoctor-diagram as a gem (directly), and to write some magic code to replace their version of plantuml with a good one (this sounds exactly like what it is : some insane black magic).

**Comment by Riduidel** [comment]
Well ... things may be easier (but awful nevertheless).
What I can do is HELL OF SIMPLE : create a fork of asciidoctorj-diagram where I use the real one as dependency, then replace plantuml version by the right one.
LET'S DO HORRIBLE THINGS!

**Comment by Riduidel** [comment]
Damn ! was able to hack my way and to rewrap the latest plantuml version in asciidoctor-diagram
But unfortunatly

    [ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:2.1.0:process-asciidoc (generate-html-doc) on project pass-archi: Execution generate-html-doc of goal org.asciidoctor:asciidoctor-maven-plugin:2.1.0:process-asciidoc failed: An API incompatibility was encountered while executing org.asciidoctor:asciidoctor-maven-plugin:2.1.0:process-asciidoc: java.lang.NoSuchMethodError: 'java.io.File net.sourceforge.plantuml.FileSystem.getCurrentDir()'

**Comment by Riduidel** [comment]
OK, I can wrap the failing version.
Now let's wrap a working one!

**Comment by Riduidel** [comment]
And it works! With the most horrible solution I've ever mavenized!

**Comment by M3lkior** [comment]
Hi @Riduidel ; seems that a similar problem happens again since few days .... the same on your side ?

```
UpdateSkinparamsAndLegendEntry("person", $PERSON_BG_COLOR, $ELEMENT_FONT_COLOR, $PERSON_BORDER_COLOR)       
$defineSkinparams($tagStereo, $bgColor, $fontColor, $borderColor, $shadowing)                               
  !$tagSkin = $elementTagSkinparams("rectangle", $tagStereo, $bgColor, $fontColor, $borderColor, $shadowing)
  !$elementSkin = "skinparam " + $element +"<<" + $tagStereo + ">> {" + %newline()                          
^^^^^                                                                                                       
 Fatal parsing error                                                                                        
37119 [INFO] Rendered /builds/yyF2GR7y/0/adeotech/adeo-services/pasq/pasq-tracks/cost-components-computer/src/docs/asciidoc/01-context.adoc
37120 [ERROR] asciidoctor: ERROR: /architecture/SystemContext.plantuml: line 0: Failed to generate image: PlantUML image generation failed: [From https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml (line 91) ]              
[From https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml (line 5) ]       
[From <input> (line 3) ]                                                                                    
                                                                                                            
@startuml(id=SystemContext)                                                                                 
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml                    
' C4-PlantUML                                                                                               
                                                                                                            
' Colors                                                                                                    
...                                                                                                         
... ( skipping 991 lines )                                                                                  
...                                                                                                         
                                                                                                            
' Colors                                                                                                    
' ##################################                                                                        
                                                                                                            
!global $PERSON_BG_COLOR = "#08427B"                                                                        
!global $PERSON_BORDER_COLOR = "#073B6F"                                                                    
!global $EXTERNAL_PERSON_BG_COLOR = "#686868"                                                               
!global $EXTERNAL_PERSON_BORDER_COLOR = "#8A8A8A"                                                           
!global $SYSTEM_BG_COLOR = "#1168BD"                                                                        
!global $SYSTEM_BORDER_COLOR = "#3C7FC0"                                                                    
!global $EXTERNAL_SYSTEM_BG_COLOR = "#999999"                                                               
!global $EXTERNAL_SYSTEM_BORDER_COLOR = "#8A8A8A"                                                           
                                                                                                            
' Styling                                                                                                   
' ##################################                                                                        
                                                                                                            
UpdateSkinparamsAndLegendEntry("person", $PERSON_BG_COLOR, $ELEMENT_FONT_COLOR, $PERSON_BORDER_COLOR)       
$defineSkinparams($tagStereo, $bgColor, $fontColor, $borderColor, $shadowing)                               
  !$tagSkin = $elementTagSkinparams("rectangle", $tagStereo, $bgColor, $fontColor, $borderColor, $shadowing)
  !$elementSkin = "skinparam " + $element +"<<" + $tagStereo + ">> {" + %newline()                          
^^^^^                                                                                                       
 Fatal parsing error      
```

**Comment by Riduidel** [comment]
Good ! I remove it immediatly !
