### ISSUE TITLE
Set current version in generated POM

### ISSUE THREAD

**Issue by douglassix-dkt** [Riduidel/agile-architecture-documentation-system#72]
When creating a new projet using the archetype, the current value of the "Agile Architecture Documentation System" should be set automatically in the generated POM instead of a fake value:

`<agile-architecture-version>master-SNAPSHOT</agile-architecture-version>`

**Comment by Riduidel** [comment]
In fact, `master-SNAPSHOT` is a valid version for a jitpack dependency, as the [jitpack site states on home page](https://jitpack.io/) :

> If the project doesn't have any GitHub Releases you can use the short commit hash or 'master-SNAPSHOT' as the version. 

But indeed, it would be better to have the artifact use a released version

**Comment by Riduidel** [comment]
Unfortunatly, I can't find any way to generate a project with the correct version number, so I'll have to leave it this way ...
